package com.keystone.orders.saga;

public enum SagaStepType {
    ORDER_CREATED,
    INVENTORY_RESERVE_REQUESTED,
    INVENTORY_RESERVED,
    INVENTORY_RESERVATION_FAILED,
    PAYMENT_AUTHORIZE_REQUESTED,
    PAYMENT_AUTHORIZED,
    PAYMENT_AUTHORIZATION_FAILED,
    INVENTORY_RELEASE_REQUESTED,
    INVENTORY_RELEASED,
    ORDER_CONFIRMED,
    ORDER_CANCELLED
}
